apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-deployment
  labels:
    app: prime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prime
  template:
    metadata:
      labels:
        app: prime
    spec:
      containers:
      - name: prime-container
        image: mkhnoori1/prime:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
